### ISSUE TITLE
Failed to create AP

### ISSUE THREAD

**Issue by nocomp** [SpyGuard/SpyGuard#1]
hi,
just tried last version of rpi (update raspbian) always get the same error
"trouble when creating  ap"
on rpi i have local ip in green showing that internet conf is ok (wlan/eth0)
any idea how i can fix this? can we hard code the fake ap somewhere?
thank you for your help super felix

**Comment by nocomp** [comment]
tried another language same issue :'(

**Comment by nocomp** [comment]
fixed,
i ve disabled and renable the nmcli

**Comment by Falstaff7** [comment]
Hi what is the procedure to disable the nmcli ?
