### ISSUE TITLE
Can't connect to SpyGuard generated Access Point

### ISSUE THREAD

**Issue by liuksovai** [SpyGuard/SpyGuard#10]
SpyGuard generates Access Points, but devices can't connect to it. It usually says that the password is incorrect, otherwise - login failed. I tried with several phones, a laptop, but it didn't work.
SpyGuard tested on laptop with Raspberry Pi Desktop - bullseye 32-bit, ubuntu-20.04.4-desktop-amd64.

**Comment by colder1989** [comment]
You can view Debug on your browser to see what's wrong...if you use Chrome just press F12 and watch the console while you try to connect...so you can see what the error is

**Comment by liuksovai** [comment]
[colder1989](https://github.com/colder1989) Thanks for the help once again and sorry for delay with answer. I will tell you my results.

1) First about info in Firefox Debug console. No errors, it shows that everything is ok, access point is created, capture token retrieved, waiting for a device to connect. No any new information appears when I try to connect with the phone.
2) I didn't get successful result in Raspberry Pi Desktop OS. I tried all the steps you mentioned. I deleted the hotspot created by SpyGuard. I created a new one in Network Manager, but the phone still did not want connect to it.
3) The situation with Ubuntu was somewhat different. Phone couldn't connect to hotpsot created by SpyGuard, but it successfully connected to hotspot, which i created via Network Manager. 
Steps i made in Ubuntu: First, opened Spyguard and generated hotspot, didn't close browser window. Second, deleted generated hotspot in Network Manager and created new one. Third, connected with phone to new hotspot. After that SpyGuard started use new manually created access point.
However, these steps must be followed every time you want to start using Spyguard.

And i think, a new problem appeared. How long it takes to analyze the data? Firefox Debug console shows lot of lines: [analysis.vue] No analysis results yet .... analysis.vue:62 I waited maybe an hour, no results.

**Comment by colder1989** [comment]
Another thing I've done besides trying to create a hotspot with network manager is to disable the virtual keyboard from the spyguard backend. I didn't think that could be the problem but you can try. For me everything works correctly, in fact by visiting some site selling spy programs it detects me correctly the report. the analysis takes me about 30 seconds or maximum 1 minutes

**Comment by ruggdoll** [comment]
there seems to be an issue with wpa_suplicant > 2.9 and Apple devices.
More here :  https://blog.incompetent.me/2023/02/ubuntu-2204-hotspot-stops-working.html

tries my self to downgrade a ubuntu 22.04 to wpa_supplicant2.9build1 ==> great success

**Comment by CSerpent** [comment]
There is an overall issue on ubuntu and its variants, non pi-desktop.  This is confirmed across Ubuntu 22.04, mint, ZorinOS etc.  I've tried the downgrade to wpa_supplicant that ruggdoll mentioned above, same issue.

The line presented in syslog:
spyguardpc wpa_supplicant[504]: Note: nl80211 driver interface is not designed to be used with ap_scan=2; this can result in connection failures

Now, here's the oddity:
I've tried this with various M.2 WiFi cards in the Dell OptiPlex 3050 MFF i3 I'm doing my non-Pi testing on - Intel AX/8260 and RTL8822.  I've also just tried with an M.2 RTL8852be - same issue.  But, if I plug in a USB RTL8852au (driver installed) and set the backend to point to that, that works without issue and without the wpa_supplicant downgrade either.

**Comment by b068931cc450442b63f5b3d276ea4297** [comment]
Hi, with the current code I have just tested it successfully on a system with Linux Mint, you can try it out to see if it works for you now. There will be some revisions soon, if there are any problems please open a new issue.
