### ISSUE TITLE
Jinja2

### ISSUE THREAD

**Issue by linepipe2563** [SpyGuard/SpyGuard#15]
Hello, 

When i update/install   Spyguard on RPI4 i have error on lauch : 
#####################################################
service spyguard-frontend status

● spyguard-frontend.service - Spyguard frontend service
     Loaded: loaded (/lib/systemd/system/spyguard-frontend.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-05-05 20:58:22 CEST; 5min ago
    Process: 411 ExecStart=/usr/bin/python3 /usr/share/spyguard/server/frontend/main.py (code=exited, status=1/FAILURE)
   Main PID: 411 (code=exited, status=1/FAILURE)
        CPU: 533ms

May 05 20:58:20 spyguard systemd[1]: Started Spyguard frontend service.
May 05 20:58:22 spyguard python3[411]: Traceback (most recent call last):
May 05 20:58:22 spyguard python3[411]:   File "/usr/share/spyguard/server/frontend/main.py", line 4, in <module>
May 05 20:58:22 spyguard python3[411]:     from flask import Flask, render_template, send_from_directory, redirect, abort
May 05 20:58:22 spyguard python3[411]:   File "/usr/local/lib/python3.9/dist-packages/flask/__init__.py", line 14, in <module>
May 05 20:58:22 spyguard python3[411]:     from jinja2 import escape
May 05 20:58:22 spyguard python3[411]: ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.9/dist-packages/jinja2/__init__.py)
May 05 20:58:22 spyguard systemd[1]: spyguard-frontend.service: Main process exited, code=exited, status=1/FAILURE
May 05 20:58:22 spyguard systemd[1]: spyguard-frontend.service: Failed with result 'exit-code'.

##########################################

pip install jinja2

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: jinja2 in /usr/local/lib/python3.9/dist-packages (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.9/dist-packages (from jinja2) (2.1.2)

**Comment by SiegfriedEhret** [comment]
Got the same.

Jinja2 is not in the requirements.txt so by default version 3.1.2 is installed. In the [requirements.txt](https://github.com/SpyGuard/SpyGuard/blob/master/assets/requirements.txt#L6) we see `flask==1.1.2`, and digging into [that version](https://github.com/pallets/flask/blob/1.1.2/setup.py#L57) shows that it actually needs `Jinja2>=2.10.1`.

I am still fixing issues with other dependencies and have not been able to run Spyguard yet... I'll let you know if I make any progress.

**Comment by SiegfriedEhret** [comment]
Yoohoo ! I got it working.
I'll dump here a few things even if I am not sure everything is needed.

First, I updated my `assets/requirements.txt` like this to install older versions of some packages:

```
ipwhois==1.2.0
pydig==0.4.0
pymisp==2.4.165.1
netaddr==0.8.0
pyyaml==5.3.1
flask==1.1.2
flask_httpauth==4.7.0
pyjwt==1.7.1
sqlalchemy==1.4.44
psutil==5.8.0
pyudev==0.24.0
qrcode==7.3.1
netifaces==0.11.0
weasyprint==57.1
python-whois==0.8.0
publicsuffix2==2.20191221
six==1.16.0
Jinja2==2.10.1
MarkupSafe==0.23
itsdangerous==0.24
Werkzeug==0.15
click==5.1
```

Then I installed [Python 3.7](https://www.python.org/downloads/release/python-3717/). Note that the end of support for this version is scheduled for 2023-06-27.

```shell
wget https://www.python.org/ftp/python/3.7.17/Python-3.7.17.tgz
tar xf Python-3.7.17.tgz
./configure
sudo make altinstall
```

Then, I used [venv](https://docs.python.org/3/library/venv.html) to create a virtual environment for Python using:

```shell
python3.7 -m venv ~/spyguard-venv
```

Then, I updated the `install.sh` file to replace every `/usr/bin/python3` with the version from the virtual environment: `/home/myuser/spyguard-venv/bin/python3`

Hope this help, good luck!

**Comment by b068931cc450442b63f5b3d276ea4297** [comment]
Hi, @SiegfriedEhret thank you for your help. With the current code, I was able to use it successfully in my tests. There will be some revisions soon, if there are any problems please open a new issue.
