### ISSUE TITLE
how to install it on a RaspBerry?

### ISSUE THREAD

**Issue by EliaWSI** [SpyGuard/SpyGuard#18]
Hi guys, i'm a young programmer and i'd like to install Spyguard on a RaspBerry but i don't really know exacly how to it.
someone could help me pls

**Comment by ruggdoll** [comment]
Just read the doc of the main page.
BUT
From a fresh raspi OS lite I had to manually install FIRST (before spyguard install) :
build-essential python3-pip libopenjp2-7 python3-cffi python3-brotli libpango-1.0-0 libpangoft2-1.0-0

and even then, I have issues on a Raspi 3

**Comment by EliaWSI** [comment]
thanks a lot ruggdoll, now my problem is to put it in kiosk mode, i've tried to follow the instructions but it seems that my "raspi-config" options are differents

**Comment by EliaWSI** [comment]
how to active "nmcli" to manage networks of a Raspberry Pi, using "raspi-config" command

**Comment by EliaWSI** [comment]
in wich mode and where can i Edit   "~/.config/lxsession/LXDE-pi/autostart" ?

**Comment by icedan** [comment]
Try Ubuntu for RPI. Mine working on RPI 5, but few steps:
apt install -y python3-pip
apt install -y network-manager
apt install -y libpangocairo-1.0-0
sudo rm -rf /usr/lib/python3.11/EXTERNALLY-MANAGED (or your version of python)
bash install.sh

**Comment by b068931cc450442b63f5b3d276ea4297** [comment]
Hi @EliaWSI , after yesterday's update venv is used for SpyGuard and the installation should work as described in the wiki.

Successfully tested with debian 11 (2023-12-05-raspios-bullseye-armhf-full) and debian 12 (2023-12-05-raspios-bookworm-arm64-full) on a Raspberry PI 4B.

In my opinion, the issue can be closed and if there are problems with the current version, a new one can be opened.

**Comment by EliaWSI** [comment]
hi, yes thats issue can be closed, finally i've installed spyguard on my raspberry...
but now i'm trying to change the name "spyguard" on the program, i tried to modify the code but it doesn't work.
do you know how can i change the name?

thanks for your time... waiting for your reply
have a good day
________________________________
Da: b068931cc450442b63f5b3d276ea4297 ***@***.***>
Inviato: giovedì 18 gennaio 2024 16:07
A: SpyGuard/SpyGuard ***@***.***>
Cc: EliaWSI ***@***.***>; Mention ***@***.***>
Oggetto: Re: [SpyGuard/SpyGuard] how to install it on a RaspBerry? (Issue #18)


Hi @EliaWSI<https://github.com/EliaWSI> , after yesterday's update venv is used for SpyGuard and the installation should work as described in the wiki.

Successfully tested with debian 11 (2023-12-05-raspios-bullseye-armhf-full) and debian 12 (2023-12-05-raspios-bookworm-arm64-full) on a Raspberry PI 4B.

In my opinion, the issue can be closed and if there are problems with the current version, a new one can be opened.

**Comment by b068931cc450442b63f5b3d276ea4297** [comment]
I send you an mail.

**Comment by EliaWSI** [comment]
Wich Mail? i didn't see

________________________________
Da: b068931cc450442b63f5b3d276ea4297 ***@***.***>
Inviato: venerdì 19 gennaio 2024 13:46
A: SpyGuard/SpyGuard ***@***.***>
Cc: EliaWSI ***@***.***>; Mention ***@***.***>
Oggetto: Re: [SpyGuard/SpyGuard] how to install it on a RaspBerry? (Issue #18)


I send you an mail.

**Comment by b068931cc450442b63f5b3d276ea4297** [comment]
I use your mail address from your [profile here](https://github.com/EliaWSI): eli***@******k.it
