### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by vicjos** [SpyGuard/SpyGuard#2]
Hi, the installation freezes always generating IOCs:

[+] Creating services
    [✔] Creating frontend service
    [✔] Creating backend service
    [✔] Creating watchers service
    [✔] Enabling services
    [✔] Starting services
[+] Feeding your SpyGuard instance with fresh IOCs and whitelist, please wait.

Another thing, but I think it should not be failing at this point of installation is that I have two eth interfaces, my idea was to change the sniff command from wlan0 to eth0 (for example).

I have Ubuntu under Vmware, with 8GB ram and 4 cpus.

Thanks,

**Comment by vicjos** [comment]
On a raspberry with wifi, if it has installed correctly, I configure the wlan to sniff and the eth to go out on the internet, I give it to generate AP and it says it is connected, but in Android and iOS the unique SSID that I have left does not appear.

(It would be great, as you wrote, if we could sniff normal network traffic, not just wifi).

Thanks a million!

**Comment by clhuby** [comment]
The problem appears to be naming used for interfaces in the script, as Ubuntu calls ethernet connections enp5s0 (or similar.) not eth0.

Syslog shows:

suricata Failure when trying to get MTU via ioctl for 'eth0' no such device (19)
suricata.service: Failed with result 'exit-code'.

This causes the installer script to hang on "Feeding your SpyGuard..."

**Comment by clhuby** [comment]
Note hitting ctrl+c at this stage, you can then open the admin webpage and set the correct interfaces.

Also make sure you have installed net-tools if on Ubuntu as some versions don't include it and it is also required for SpyGuard to work and not installed by the script.

**Comment by JeanLucRouinvy** [comment]
This tool scope is great, but sadly we were not able to make it running, tried on many different platforms. Is it possible to provide a more comprehensive list of requirements / install tutorial?
All services fails to run, no error in the log, nothing to share.

**Comment by tdm31** [comment]
thank you for your reply. I managed to make the fork spyguard work on lubuntu with also worries but less.

**Comment by speremma** [comment]
Has anyone succeeded in installing and having it working on Ubuntu running in VMware? Thank you.
