### ISSUE TITLE
Raspbian 5.1 / Ubuntu 23 - pip no works without venv

### ISSUE THREAD

**Issue by CSerpent** [SpyGuard/SpyGuard#21]
https://www.reddit.com/r/Python/comments/1338oge/you_cant_use_pip_on_ubuntu_2304_anymore/ refers - pip can no longer be used to install systemwide and therefore SpyGuard cannot be installed as currently stands

Whilst some modules are installable from apt, eg sqlalchemy (using python3-sqlalchemy) and weasyprint without the prefix, the following have no apt installable modules:
ipwhois
pydig
pymisp
pyyaml
flask_httpauth
pyjwt
python-whois
pyOpenSSL

**Comment by CSerpent** [comment]
Icedan mentioned this fix on https://github.com/SpyGuard/SpyGuard/issues/18#issuecomment-1823490742

_apt install -y python3-pip
apt install -y network-manager
apt install -y libpangocairo-1.0-0
sudo rm -rf /usr/lib/python3.11/EXTERNALLY-MANAGED (or your version of python)
bash install.sh_

If performed in sudo this does seem to work.

**Comment by b068931cc450442b63f5b3d276ea4297** [comment]
Hi @CSerpent, after yesterday's update venv is used for SpyGuard.

Successfully tested with debian 11 (2023-12-05-raspios-bullseye-armhf-full) and debian 12 (2023-12-05-raspios-bookworm-arm64-full) on a Raspberry PI 4B. 

In my opinion, the issue can be closed and if there are problems with the current version, a new one can be opened.

**Comment by CSerpent** [comment]
I'd agree, built working perfectly on Pi 5 with 2023-12-05-raspios-bookworm-arm64-full
