### ISSUE TITLE
Wifi éphémère

### ISSUE THREAD

**Issue by fred86000** [SpyGuard/SpyGuard#34]
Bonjour 

Spyguard installé sur un Rasperry Pi. 
Network manage activé
Blanchement en ethernet
Choux des réseaux : wlan - eth0

Cependant Spyward ne me génère pas de wifi éphémère

Merci de votre aide

**Comment by b068931cc450442b63f5b3d276ea4297** [comment]
Hi, can you please specify which Raspberry Pi, which operating system on the Raspberry Pi and which version of SpyGuard  is used? Were any errors displayed?

**Comment by fred86000** [comment]
Bonjour 
Il s'agit du Raspberry PI 3 - OS : Debian Bullseye 32 bit - Spyguard 1.0
Aucun message d'erreur mais Spyguard essaye de généré un wifi éphémère sans succès. 
J'ai activé la détection du réseau Wifi 'Turn ON wireless wifi' . le raspberry se connecte dessus et me le propose en réseau éphémère. Cependant rien ne se passe quand mon smartphone se connecte a ce réseau wifi. Tout est hyper lent. 

Merci de votre aide

**Comment by tonytruand92** [comment]
Je viens de m'installer Spyguard sur un RPI 4 OS : Debian Bookworm 64bit
Après le lancement, la génération de l'AP se passe bien (activée, on peut s'y connecter : mais il faut au préalable aller regarder dans la config réseau via X pour connaitre le pass....), puis rien du tout, ça ne franchi pas l'étape suivante.
Je sais pas si on est dans la même situation ?
Spyguard reste figé sur la page de génération de l'AP.

**Comment by felixaime** [comment]
Chelou, le thread est bien vieux, je sais pas si t'as réussi à enfin installer mais en théorie cela devrait bien fonctionner. Je ferme le thread, n'hésites pas à me ping sur l'adresse dans le readme au cas ou. Félix
