### ISSUE TITLE
plus de report.pdf dans la sauvegarde

### ISSUE THREAD

**Issue by f5jie** [SpyGuard/SpyGuard#41]
Bonjour,
Installé sur un Ubuntu 22.04, tout est OK
Mais installé sur Ubuntu 24.04 ; 
- génération du hotspot wifi OK
- analyse OK
- mais : lors de la sauvegarde, le PCAP OK le répertoire "assets" OK mais plus de fichier report.pdf !
Mais maintenant spyguard utilise un environnement virtuel Python...
JPM

**Comment by f5jie** [comment]
Résolu.
Il y avait un conflit entre le package "weasyprint.deb" installé par "apt install weasyprint" et
le module python "weasyprint" installé par "pip3 install weasyprint".
Seule le module est nécessaire, tout est maintenant OK après "apt remove weasyprint", "pip3 uninstall weasyprint" puis "pip3 install weasyprint".
JPM

**Comment by HonourableTyr** [comment]
I may sound like a complete idiot, but I cannot follow these steps to fix the issue on Ubuntu. I get an error whenever I run the pip3 commands.

I do not know how to specify the virtual environment that was set up during the installation of SpyGuard. Could you be more specific as to how you fixed this?
